# specify compose version
# version: "3.9" >> obsolete

# sets the docker service scaffold
# each service represents one container
services:

  # defines the container name
    web:
      # takes the build being done by the Dockerfile in the current directory (.)
      build: .
      # defines the container name explicitly
      container_name: web
      # defines the .env location to reference ports and other attributes that was defined in env file
      env_file: ".env"
      # defines port from inside and outside connection from the env file
      ports:
        - "${PORT}:${PORT}"
      # defines the port number explicitly
      #ports: '3000:3000'
      # ensures that the container restarts automatically if exits unexpectedly'
      restart: always
  